apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dqa-demo-test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 1=registry.sikalabs.com/examples/2023-05-26-dqa-k8s-demo:test
    argocd-image-updater.argoproj.io/1.helm.image-spec: image
    argocd-image-updater.argoproj.io/1.update-strategy: digest
    argocd-image-updater.argoproj.io/1.force-update: 'true'
    argocd-image-updater.argoproj.io/1.platforms: linux/amd64
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: dqa-demo-test
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2023-05-26-dqa-k8s-demo.git
    targetRevision: HEAD
    path: charts/dqa-demo
    helm:
      releaseName: dqa-demo-test
      values: |
        host: dqa-demo-test.k8s.sikademo.com
        replicas: 10
        image: registry.sikalabs.com/examples/2023-05-26-dqa-k8s-demo:test
