apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dqa-demo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: dqa-demo-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2023-05-26-dqa-k8s-demo.git
    targetRevision: HEAD
    path: charts/dqa-demo
    helm:
      releaseName: dqa-demo-dev
      values: |
        host: dqa-demo-dev.k8s.sikademo.com
        replicas: 3
        image: sikalabs/hello-world-server:v0.6.0
